#!/bin/bash

echo "✅ INFORMATIONS AJOUTÉES DANS CHAQUE MESSAGE AU BOT"
echo ""
echo "📋 Données maintenant incluses dans chaque requête webhook :"
echo ""
echo "🔹 conversation_id : ID de la session de chat"
echo "🔹 user_id : ID de l'utilisateur" 
echo "🔹 tokens_used : Estimation basée sur la longueur du message"
echo "🔹 message_length : Longueur exacte du message"
echo "🔹 history_count : Nombre de messages dans l'historique"
echo "🔹 timestamp : Horodatage de l'envoi"
echo ""
echo "📊 EXEMPLE DE PAYLOAD ENVOYÉ AU WEBHOOK :"
echo ""
echo "{"
echo "  \"body\": {"
echo "    \"message\": \"Bonjour, comment ça va ?\","
echo "    \"userId\": \"user-abc-123\","
echo "    \"user_id\": \"user-abc-123\","
echo "    \"sessionId\": \"session-def-456\","
echo "    \"conversation_id\": \"session-def-456\","
echo "    \"tokens_used\": 6,"
echo "    \"message_length\": 25,"
echo "    \"history_count\": 2,"
echo "    \"timestamp\": \"2026-03-09T18:00:00.000Z\","
echo "    \"history\": [...]"
echo "  }"
echo "}"
echo ""
echo "🔍 LOGS DE DEBUG ACTIVÉS :"
echo "Ouvrez la console du navigateur (F12) pour voir :"
echo "- [WEBHOOK] Données envoyées: { conversation_id, user_id, tokens_used... }"
echo ""
echo "🧪 POUR TESTER :"
echo "1. Ouvrez http://localhost:5174"
echo "2. Connectez-vous et envoyez un message"
echo "3. Regardez la console pour vérifier les données"